# Generated by Django 4.1.7 on 2023-05-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_delete_uploaded_order_aadhar_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbike',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='orderbike',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='orderbike',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='orderbus',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='orderbus',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='orderbus',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
